<a href="https://colab.research.google.com/github/NarendraPati1/AI-ML/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU :{torch.cuda.get_device_name(0)}")
else :
  print (" GPU not available")

 GPU not available


##Creating tensor

In [ ]:
##empty
a= torch.empty(2,3)


In [ ]:
##check type
type(a)

torch.Tensor

In [ ]:
#zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.0714, 0.0361, 0.5255],
        [0.0028, 0.3003, 0.5712]])

In [ ]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#custom tensor
a=torch.tensor([1,2,3])

In [ ]:
a.shape

torch.Size([3])

In [ ]:
torch.ones_like(a)

tensor([1, 1, 1])