<a href="https://colab.research.google.com/github/NarendraPati1/AI-ML/blob/main/pytorch/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#loss calculate
def binary_cross_entropy_loss(prediction , target):
  epsilon  = 1e-8
  prediction = torch.clamp(prediction,epsilon, 1-epsilon)
  return -((target*torch.log(prediction))+ (1-target) * torch.log(1-prediction))


In [ ]:
x= torch.tensor(6.7)
y=torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z= w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
 loss.backward()

In [ ]:
w.grad
b.grad

tensor(0.9988)

In [ ]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


##Vector

In [ ]:
x = torch.tensor([1.0,2.0,3.0], requires_grad = True )
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([1.3333, 2.6667, 4.0000])

In [ ]:
x.grad.zero_()

tensor([0., 0., 0.])